var mongoose = require('mongoose');

var Schema = mongoose.Schema;

//Define the Schema

var OrderSchema = Schema (

  {
    customerId: { type:String, required: true }, // Generated by the session
    dateCreated: { type: Date, default: Date.now }, // Use date() javascript
    shippingAddress: { type:String, required: true }, // Use form  address
    products: [{}], // Cart session
    quantity: { type:Number, required:true}, // Cart session
    orderStatus: { type:String,  enum: ['orderPlaced','picked', 'packed', 'dispatched', 'delivered'], required:true } // Set by warehouse 

  }

);

var Order = mongoose.model('Order', OrderSchema);

//Export model
module.exports = Order;
